### PR TITLE
Features/3 setup testing

### LINKED ISSUE #3: [Chore] Setup Testing

### PR DESCRIPTION
**Pull request by TheBeege**
Closes #3 
- Added unit tests
- Converted to TypeORM
- Added migrations

### CODE REVIEW

**Comment by TheBeege** [comment]
@kzkaneoka Can I get a review? I changed how things work

**Comment by kzkaneoka** [comment]
@TheBeege Quick question just in case. when running `npm run start:dockerLocal` locally, I got:

```
Error during migration run:
Error: connect ECONNREFUSED 172.27.0.2:3306
```

Am I doing wrong, or will this be done by [[Chore] Setup Proper Database Migration #4](https://github.com/CodeSeoul/event_member_management/issues/4)? If so, LGTM.

**Comment by TheBeege** [comment]
@kzkaneoka Ah... I believe that's due to the migration container coming up before the database container has gotten up and running. I'll come up with a way to make that more reliable today. Until then, if you run it a second time, it should work well. Were you able to get it running that way?

**Comment by TheBeege** [comment]
@kzkaneoka Try now. I want to make sure that part is working before we merge.

**Comment by kzkaneoka** [comment]
@TheBeege I could run it from my end. Thanks!

P.S., please let me know if I should/am allowed to merge PR.

**Comment by TheBeege** [comment]
@kzkaneoka Feel free to. I've added you to the team with proper permissions. I think the only strong rule we should have is that people shouldn't merge their own code. So please merge whenever you're ready.

**Comment by kzkaneoka** [comment]
@TheBeege Merged!

**Pull request merged**
