### PR TITLE
Added Swagger documentation

### LINKED ISSUE #5: [Chore] Setup Swagger Documentation

### PR DESCRIPTION
**Pull request by TheBeege**
Closes #5.

- Reorganized routing system into a centralized router imported by app, rather than importing various routers in app directly.
- Setup Swagger model definitions in separate file for each entity.
- Added Joi validations for various endpoints, which also generates Swagger documentation.
- Setup Swagger spec file at /docs/spec.json and Swagger UI at /docs
- Updated CONTRIBUTING.md to match changes

### CODE REVIEW

**Comment by kzkaneoka** [comment]
Hi @TheBeege, when I run `docker-compose up` w/o `-d` option, I got:

> Error: Cannot find module '@hapi/joi'

I deleted `node_modules` directory, and re-install dependencies using `npm install`, and also, `npm ci`. However, the error still happened. Would you be able to check on it if you have the same error?

**Comment by TheBeege** [comment]
@kzkaneoka I can't reproduce that behavior. I also removed `node_modules` and reinstalled. I ran `docker-compose up` outside of npm with success. I ran it on my shell directly, not in my IDE, though both should work.

If it's still happening, can you show me a stacktrace?

**Comment by kzkaneoka** [comment]
Um, it's wired. This is the stacktrace, and as well as git log.

image

image

**Comment by kzkaneoka** [comment]
Thanks for working. LGTM!

**Pull request merged**
